# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 469587f00c61f8de76e7fb1e67c6c9da37da3056afa876f9dd3f40411fd57f36014de37cba00ce3d23d00758a4630d3c084042a03cb0135ed633651fa74cb7d7

test:
  secret_key_base: 497fe682a236f2d2acb07d0cb5215d70f2a7448e947a3dba2513203ce184e79d9e76f59ef0cb7150f4469c5a030e7f0c7e5fd3b93ad44e3e0edb456fe5f655e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
